version: 0.2

phases:
  pre_build:
    commands:
      - echo "##### aws ecr login"
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "##### install jq"
      - apt install jq
      - echo "##### set IMAGE_TAG"
      - export IMAGE_TAG=$(curl -s https://api.github.com/repos/nginxinc/docker-nginx/tags | jq -r .[0].name)
      - echo "##### echo IMAGE_TAG"
      - echo $IMAGE_TAG
  build:
    commands:
      - echo "##### pwd"
      - pwd
      - echo "##### ls"
      - ls
      - echo "##### cd"
      - cd "mainline/alpine"
      - echo "##### docker build"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f ./myDockerfile .
      - echo "##### docker tag"
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo "##### docker push"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

